# Documentation reference https://github.com/golangci/golangci-lint/blob/v2.0.2/.golangci.reference.yml
version: "2"
run:
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
    text:
      path: stdout
      colors: true
      print-issued-lines: true
      print-linter-name: true

formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/migtools/oadp-non-admin)
    gofmt:
      simplify: true

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - ginkgolinter
    - goconst
    - goheader
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - loggercheck
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
  settings:
    dogsled:
      max-blank-identifiers: 2
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 3
      min-occurrences: 5
    goheader:
      # copy from ./hack/boilerplate.go.txt
      template: |-
        Copyright 2024.

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
    govet:
      enable-all: true
    importas:
      no-unaliased: true
      alias:
        - pkg: github.com/vmware-tanzu/velero/pkg/apis/velero/v1
          alias: velerov1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: github.com/migtools/oadp-non-admin/api/v1alpha1
          alias: nacv1alpha1
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    nolintlint:
      allow-unused: false
      allow-no-explanation: []
      require-explanation: true
      require-specific: true
    revive:
      enable-all-rules: true
      rules:
        - name: line-length-limit
          disabled: true
        - name: function-length
          disabled: true
        - name: max-public-structs
          disabled: true
        # TODO remove
        - name: cyclomatic
          disabled: true
        - name: cognitive-complexity
          disabled: true
    unparam:
      check-exported: true
  exclusions:
    paths:
      - test/*
    rules:
      - linters:
          - revive
        text: "^struct-tag: unknown option 'inline' in JSON tag$"
      - linters:
          - revive
        text: "^add-constant: avoid magic numbers like '0', create a named constant for it$"
      - linters:
          - revive
        text: "^add-constant: avoid magic numbers like '1', create a named constant for it$"

issues:
  uniq-by-line: true
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default: error
