apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: fs-nonadminbackup
objects:
  - apiVersion: nac.oadp.openshift.io/v1alpha1
    kind: NonAdminBackup
    metadata:
      name: nonadminbackup-sample-${SUFFIX}
      namespace: ${NAMESPACE}
    spec:
      backupSpec:
        includedNamespaces:
          - ${NAMESPACE}
        defaultVolumesToFsBackup: true
parameters:
  - description: NonAdminBackup suffix
    from: '[a-z0-9]{8}'
    generate: expression
    name: SUFFIX
  - description: NonAdminBackup namespace
    name: NAMESPACE
    value: mysql-persistent
