# permissions for end users to edit nonadminrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nonadminrestore-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oadp-nac
    app.kubernetes.io/part-of: oadp-nac
    app.kubernetes.io/managed-by: kustomize
  name: nonadminrestore-editor-role
rules:
- apiGroups:
  - oadp.openshift.io
  resources:
  - nonadminrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oadp.openshift.io
  resources:
  - nonadminrestores/status
  verbs:
  - get
