# permissions for end users to view nonadminbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nonadminbackup-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oadp-nac
    app.kubernetes.io/part-of: oadp-nac
    app.kubernetes.io/managed-by: kustomize
  name: nonadminbackup-viewer-role
rules:
- apiGroups:
  - oadp.openshift.io
  resources:
  - nonadminbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oadp.openshift.io
  resources:
  - nonadminbackups/status
  verbs:
  - get
