name: OADP version compatibility check

on:
  push:
    branches:
      - master
      # add release branches
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 00:00 UTC

jobs:
  golang-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        oadp-version: [
          "master",
          # add release branches
        ]

    steps:
      - name: Checkout OADP operator
        uses: actions/checkout@v4
        with:
          repository: openshift/oadp-operator
          ref: ${{ matrix.oadp-version }}

      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Checkout Non Admin Controller (NAC)
        uses: actions/checkout@v4
        with:
          repository: migtools/oadp-non-admin
          ref: ${{ matrix.oadp-version }}
          path: oadp-non-admin

      - name: Check Non Admin Controller (NAC) manifests
        run: |
          NON_ADMIN_CONTROLLER_PATH=./oadp-non-admin make update-non-admin-manifests
          test -z "$(git status --short -- ':!oadp-non-admin')" || (echo "run 'make update-non-admin-manifests' in OADP repository to update Non Admin Controller (NAC) manifests" && exit 1)
